'use strict';
var assert = require('assert');
var settings = require('../src/pkjs/lib/settings');
var memory = {};
var storage = {getItem: function(key) { return memory[key] || null; }, setItem: function(key, value) { memory[key] = value; }};
assert.strictEqual(settings.validate({}).missing, true);
assert.strictEqual(settings.validate({address: 'https://bad:443', token: 'x'}).ok, false);
assert.strictEqual(settings.validate({address: 'localhost:8080', ssl: false, token: 'tb_x'}).ok, true);
settings.save(storage, {address: 'localhost:8080', ssl: false, token: 'tb_secret'});
assert.strictEqual(settings.fromClay({CONFIG_ADDRESS: 'localhost:8080', CONFIG_SSL: false, CONFIG_TOKEN: ''}, settings.load(storage)).token, 'tb_secret');
require('./runtime_test');
require('./api_test');
require('./text_test');
require('./codec_test');
require('./transport_test');
require('./reader_test');
require('./contract_test');
process.stdout.write('PKJS tests passed\n');
